version: '3' 

services:
  xwiki:
    image: xwiki:stable-postgres-tomcat
    container_name: xwiki
    ports:
      - "8082:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=Zx0812851375
      - DB_DATABASE=xwiki
      - DB_HOST=xwiki-postgres 
    depends_on:
      - xwiki-db
    volumes:
      - /home/docker/xwiki:/usr/local/xwiki

  xwiki-db:
    image: postgres:16
    container_name: xwiki-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_PASSWORD=Zx0812851375
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - /home/docker/postgres/xwiki:/var/lib/postgresql/data

